"""Generate a results-grounded simulation section and compile a standalone preview.

The preview is not a substitute for integrating and compiling the user's current
theoretical manuscript. That integration requires its identified source tree.
"""
import argparse
import json
from pathlib import Path
import subprocess

import pandas as pd


SECTION = r'''
\section{Simulation: a balanced three-factor economy}
\label{sec:balanced_simulation}
We study direct portfolio learning in a stock-level economy with three economic
factors. The managed spectrum is generated by the characteristic distribution
and the Mat\'ern kernel. Numerical kernel rank is distinct from the number of
economic factors. Table~\ref{tab:sim_calibration} gives the frozen calibration.

\subsection{Characteristics, returns, and the population policy}
There are $N=3G$ stocks and $D=6$ characteristics. Independent group-level states
start from $S_{g,d,0}\sim N(0,1)$ and evolve as
\[
S_{g,d,t+1}=\rho_d S_{g,d,t}+\sqrt{1-\rho_d^2}\,\eta_{g,d,t+1},
\qquad \eta_{g,d,t+1}\sim N(0,1).
\]
With $U_{g,d,t}=\Phi(S_{g,d,t})$, the three roles in group $g$ have
\[
Z_{g,r,d,t}=2\bigl((U_{g,d,t}+r/3)\bmod 1\bigr)-1,
\qquad r=0,1,2.
\]
The same phase shift applies to every coordinate. These population ranks have a
continuous uniform distribution on the cube; they are not empirical ranks.
Writing $u(z)=(z_1+1)/2$, define
\[
\beta(z)=\sqrt{c_\beta}
\begin{pmatrix}
\sqrt{2/3}\cos(2\pi u(z))\\
\sqrt{2/3}\sin(2\pi u(z))\\
1/\sqrt 3
\end{pmatrix}.
\]
The trigonometric identities for three equally spaced phases imply
$\|\beta(z)\|^2=c_\beta$ and
$B_t'B_t/N=\Gamma_\beta=(c_\beta/3)I_3$ at every date.
Independent next-period shocks satisfy
\[
F_{t+1}\sim N(\mu_F,I_3-\mu_F\mu_F'),\qquad
\varepsilon_{t+1}\sim N(0,\sigma_\varepsilon^2 I_N),\qquad
R_{t+1}=B_tF_{t+1}+\varepsilon_{t+1}.
\]
Thus $\mathbb E[F_{t+1}F_{t+1}']=I_3$ is a second-moment normalization.
The conditional mean and second moment of stock returns are
$m_t=B_t\mu_F$ and $S_t=B_tB_t'+\sigma_\varepsilon^2I_N$.

For the paper's weights $w_t(W)=W(Z_t)/N$, minimizing
$\mathbb E[(1-w_t(W)'R_{t+1})^2\mid\mathcal F_t]$
gives $S_tw_t^\star=m_t$. The identity
\[
(BB'+\sigma^2 I)^{-1}B=B(B'B+\sigma^2 I_3)^{-1}
\]
and exact cross-sectional balance therefore yield
\[
w_t^\star=\frac1N B_t
\left(\Gamma_\beta+\frac{\sigma_\varepsilon^2}{N}I_3\right)^{-1}\mu_F,
\qquad
W^\star(z)=\frac{\beta(z)'\mu_F}{c_\beta/3+\sigma_\varepsilon^2/N}.
\]
The population policy is derived from the return model and the loss; it is not
an independently imposed simulation target. With $g=c_\beta/3$,
\[
q^\star=\frac{g}{g+\sigma_\varepsilon^2/N}\|\mu_F\|^2,\quad
Q(W^\star)=1-q^\star,\quad
(\operatorname{SR}^\star)^2=\frac{q^\star}{1-q^\star}.
\]

\subsection{Assumption audit and spectrum}
Stationary initialization and stable Gaussian AR dynamics give geometric
beta-mixing; measurable rank and phase maps and independent next-period shocks
preserve this property (E1). For $A_t=K_t/N^2$, the exact noncentral Gaussian
quadratic-form MGF verifies
\[
\log\mathbb E\!\left[\exp\left(R_{t+1}'A_tR_{t+1}/B_X^2\right)
\mid\mathcal F_t\right]\leq\tfrac12,
\qquad B_X^2=4(c_\beta+\sigma_\varepsilon^2).
\]
Conditional scalar Gaussian moments give $K_4=3$ (E2). The explicit sine,
cosine, and constant loading functions have smooth extensions on the bounded
cube. They belong to the Sobolev space of order $\nu+D/2=9/2$, equivalent to
the Mat\'ern-$3/2$ RKHS, as does their fixed linear combination $W^\star$ (E3).
The conditional pricing restriction follows from
$v_t'(m_t-S_tw_t^\star)=0$ for every admissible $v_t$ (E4).

For the uncentered managed second-moment operator,
\[
\frac{\sigma_\varepsilon^2}{N}T_K\preceq\Sigma_{\mathcal H_K}
\preceq\left(c_\beta+\frac{\sigma_\varepsilon^2}{N}\right)T_K.
\]
The lower term is the idiosyncratic contribution; the upper bound follows by
Jensen's inequality and $\|\beta\|^2=c_\beta$. Thus the managed spectrum has
the Mat\'ern exponent $b=1+2\nu/D=3/2$ (E5). The finite-sample audit uses one
independent population quadrature with 3,072 nodes, including the within-triplet
dependence, and tests the Loewner and ordered-eigenvalue bounds. Log-log fits use
the fixed windows 30--200, 60--400, and 120--800. These finite-resolution fits do
not prove an asymptotic exponent. The analytic optimal Sharpe is positive and
finite and is compared with a 100,000-period stock-return simulation (E6).

\subsection{Estimation, selection, and evaluation}
We use the paper's response-one ridge estimator in a controlled Nystr\"om
subspace of the actual Mat\'ern RKHS, without rescaling the kernel diagonal.
The inducing points are independent of all training and OOS samples. Empirical
effective complexity is
\[
\widehat{\mathcal C}(\lambda)=\operatorname{Tr}
\bigl[\widehat\Sigma_T(\widehat\Sigma_T+\lambda I)^{-1}\bigr].
\]
Training sample sizes and all 96 positive penalties are fixed before simulation.
Every replication generates genuine stock-level returns. Sample-size paths are
nested within a replication; different replications are independent. Validation
uses the last quarter of the available history, following an earlier training
block. After selecting lambda by validation loss, the policy is refitted on all
available observations. An independent 720-period block gives OOS loss and
unannualized Sharpe. Neither population moments, $W^\star$, nor OOS data enter
selection. Separate independent population quadrature integrates conditional
factor and idiosyncratic moments for more precise population-risk evaluation.

The population-risk oracle minimizes mean regret over the same fixed grid.
Boundary choices and all high-complexity observations are retained. We report
means, medians, pointwise Monte Carlo intervals, selection frequencies, and
benchmarks for strong shrinkage, near-unregularized policies, a validated affine
characteristic policy, and equal weights.
Selected-penalty rate regressions use Monte Carlo means. The selection panel in
the main complexity figure displays the median penalty; reporting both retains
the effect of skewness and boundary choices rather than conflating the two.

For each penalty, the exact decomposition in the numerical subspace is
\[
Q(\widehat W_\lambda)-Q(W^\star)
=\{Q(W_\lambda)-Q(W^\star)\}
+\|\widehat W_\lambda-W_\lambda\|_{\Sigma}^2
+2\langle\widehat W_\lambda-W_\lambda,
\Sigma W_\lambda-\mu\rangle.
\]
The cross term is signed; only the squared-norm estimation term is necessarily
nonnegative. Population bias includes the explicitly measured numerical
approximation floor. Rank sensitivity compares 128, 256, and 512 inducing points.
For numerical rank $r$, empirical complexity cannot exceed $\min(T,r)$.
The near-unregularized end of each curve is therefore a subspace diagnostic
and can be rank-sensitive. The paired acceptance check concerns oracle and
validation-selected regret; it is not a uniform approximation guarantee over
the entire penalty grid or an infinite-rank asymptotic experiment.

\subsection{Monte Carlo evidence and limits}
RESULTS_PARAGRAPH

Rate regressions use the full T grid, its upper half, and its largest four values.
Bootstrap intervals resample entire independent replications, preserving their
joint T-by-lambda surfaces and recomputing both the oracle and validation choices.
The displayed theoretical slopes are benchmarks for the theory's risk envelope;
they are not imposed DGP-specific equalities for this fixed smooth population
policy. Slower convergence, boundary selections, and differences from benchmark
slopes are reported without modifying the calibration or fitting windows.

ROBUSTNESS_PARAGRAPH

\input{\simoutput/tables/table1_calibration.tex}
\input{\simoutput/tables/table2_assumptions.tex}
\input{\simoutput/tables/table3_main_results.tex}
\input{\simoutput/tables/table4_rates.tex}
\input{\simoutput/tables/table5_robustness.tex}
'''


def generate_section(output, profile='paper'):
    if profile == 'confirmation_v2':
        from simulations.paper_confirmation import generate
        return generate(output)
    output = Path(output).resolve()
    if profile == 'paper':
        verification = output/'audit/final_numerical_verification.json'
        if not verification.exists() or not json.loads(verification.read_text()).get('passed'):
            raise ValueError('The production paper section requires the complete numerical acceptance audit.')
    directory = output/'paper'
    directory.mkdir(parents=True, exist_ok=True)
    main = pd.read_csv(output/'data/baseline/main_results.csv')
    rates = pd.read_csv(output/'data/baseline/rates.csv')
    last = main.iloc[-1]
    R = int(last.replications)
    paragraph = (f"The headline uses {R} independent replications. At $T={int(last['T'])}$, "
                 f'mean oracle and validation-selected population losses are {last.oracle_population_loss:.6f} '
                 f'and {last.selected_population_loss:.6f}; their mean population Sharpes are '
                 f'{last.oracle_population_sharpe:.5f} and {last.selected_population_sharpe:.5f}. '
                 f'Mean empirical complexities are {last.oracle_complexity:.3f} and {last.selected_complexity:.3f}. '
                 f'The selected-to-oracle mean regret ratio is {last.selected_oracle_regret_ratio:.3f}. '
                 f'The validation boundary-selection frequency is {100*last.boundary_selection_frequency:.1f} percent. '
                 f'The ensemble oracle selects a grid boundary at {int(main.oracle_on_boundary.sum())} of '
                 f'{len(main)} sample sizes. These observations are retained in all plots and rate regressions.')
    if profile=='smoke':
        paragraph = '\\textbf{Smoke-test preview only; these are not production paper results.} '+paragraph
        robustness = 'The full robustness design is predeclared but is not represented by this smoke-test preview.'
    else:
        curves = pd.read_csv(output/'data/baseline/curves.csv')
        curve = curves[curves['T']==last['T']].sort_values('complexity_mean')
        minimum = curve.loc[curve.oos_loss_mean.idxmin()]
        peak = curve.loc[curve.oos_sharpe_mean.idxmax()]
        paragraph += (f' Along the full largest-T grid, mean independent OOS loss is '
                      f'{curve.iloc[0].oos_loss_mean:.6f} at the lowest represented complexity and '
                      f'{curve.iloc[-1].oos_loss_mean:.6f} at the highest. Its observed grid minimum is '
                      f'{minimum.oos_loss_mean:.6f} at mean empirical complexity {minimum.complexity_mean:.3f}. '
                      f'The observed mean OOS Sharpe maximum is {peak.oos_sharpe_mean:.5f} '
                      f'at complexity {peak.complexity_mean:.3f}. These OOS extrema are descriptive '
                      'and never determine a fitted policy or a validation choice.')
        full = rates[(rates.quantity=='oracle_regret') & (rates.window=='full')].iloc[0]
        upper = rates[(rates.quantity=='oracle_regret') & (rates.window=='upper_half')].iloc[0]
        paragraph += (f' The oracle-regret log-log slope is {full.OLS_slope:.3f} over the full grid '
                      f'(whole-replication bootstrap interval [{full.bootstrap_low:.3f}, {full.bootstrap_high:.3f}]) '
                      f'and {upper.OLS_slope:.3f} over its predeclared upper half '
                      f'([{upper.bootstrap_low:.3f}, {upper.bootstrap_high:.3f}]). '
                      'The difference between these windows shows the finite-sample transition; '
                      'neither window nor the calibration was selected to match the theoretical slope.')
        robustness = (r'Robustness varies N independently of T, signal strength and idiosyncratic noise, '
            r'characteristic persistence, and Mat\'ern smoothness. All 15 additional configurations use '
            r'200 replications. Nearby multiples of three, $N\in\{99,300,501,999\}$, preserve exact triplet balance. '
            r'The weak/high-noise case uses $\mu_F/2$ and $\sigma_\varepsilon=0.12$; '
            r'the strong/low-noise case uses $2\mu_F$ and $\sigma_\varepsilon=0.04$. '
            r'Persistence is $\rho\in\{0.70,0.90,0.97\}$ and the alternative kernel smoothness values '
            r'are $\nu\in\{0.5,2.5\}$ at the same dimension $D=6$. '
            r'Empirical ranks are a separate finite-support experiment that violates the infinite-spectrum E5 condition. '
            r'They use coordinatewise midranks $2(\operatorname{rank}(Z_i)-1/2)/N-1$ and retain E1--E4 and E6. '
            r'Bounded heteroskedastic Gaussian shocks retain tail control but generally destroy the baseline '
            r'conditional pricing identity; their conditional standard deviation is '
            r'$\sigma_\varepsilon(z)=0.08\exp(0.35z_2)$. E1 and E2 remain exact, and bounded positive '
            r'volatility preserves the E5 operator comparison with adjusted constants. E3 and E6 for '
            r'the unrestricted heteroskedastic optimum are not asserted. Their regret is explicitly measured against the numerical population '
            r'optimum in the same Nystr\"om subspace, not the baseline analytic optimum. The empirical JKP '
            r'exercise is distinct from all of these artificial economies.')
    text = SECTION.replace('RESULTS_PARAGRAPH', paragraph).replace('ROBUSTNESS_PARAGRAPH', robustness)
    config = json.loads((output/'run_manifest.json').read_text())['configuration']
    text = text.replace('all 96 positive penalties', f"all {len(config['penalties'])} positive penalties")
    text = text.replace('720-period', f"{config['oos_periods']}-period")
    if profile=='smoke':
        text = text.replace('Rate regressions use the full T grid, its upper half, and its largest four values.', 'This smoke preview fits only predeclared windows containing at least three sample sizes; the full paper profile additionally uses the upper-half and largest-four windows.')
    figures = [('baseline_four_panel','Independent OOS performance against empirical effective complexity. All penalties are retained; loss uses a logarithmic scale.'),
               ('bias_estimation_regret','Exact bias, signed estimation contribution, and total regret. A symmetric logarithmic scale retains negative cross terms.'),
               ('population_spectrum','Population kernel and managed spectra on common independent quadrature. Shaded fixed windows show spectral-fit sensitivity.'),
               ('rate_laws','Oracle and validation rate paths. Dashed curves display theoretical slope benchmarks without constraining fitted results.')]
    if profile=='paper':figures.append(('main_robustness','Signal-to-noise robustness with the same fixed learning design.'))
    for name, caption in figures:
        text += ('\n\\begin{figure}[p]\n\\centering\n\\includegraphics[width=\\textwidth]{\\simoutput/figures/'+name+'.pdf}\n'
                 '\\caption{'+caption+'}\n\\label{fig:sim_'+name+'}\n\\end{figure}\n')
    appendix = r'''
\clearpage
\section*{Simulation appendix}
Population evaluation uses independent group quadrature. In orthonormal
Nystr\"om coordinates $\phi(z)$, write
$H_g=\frac13\sum_r\phi(Z_{g,r})\beta(Z_{g,r})'$ and
$\overline H=M^{-1}\sum_g H_g$. Then
\[
\widehat\Sigma=\frac{\sigma_\varepsilon^2}{N}\widehat T_K
+\frac1{GM}\sum_g H_gH_g'
+\left(1-\frac1G\right)\overline H\overline H',
\qquad
\widehat T_K=\frac1{3M}\sum_{g,r}\phi(Z_{g,r})\phi(Z_{g,r})'.
\]
This integrates the factor and idiosyncratic shocks analytically while preserving
within-triplet dependence. The quadrature distribution is independent of all
training paths and cannot affect validation choices. For empirical ranks, full
independent cross-sections are integrated because ranking couples groups.
For heteroskedasticity, the idiosyncratic term uses the actual bounded
state-dependent conditional variance.
'''
    if profile == 'paper':
        population = json.loads((output/'data/baseline/population.json').read_text())
        appendix += (f'\nThe headline population quadrature estimates the regret floor of the '
                     f'unregularized rank-256 subspace at {population["subspace_regret_floor"]:.8f}. '
                     'This approximation floor is included in every displayed population-bias curve.\n')
        rank = pd.read_csv(output/'audit/approximation_rank.csv')
        largest = rank.loc[rank['rank']==512, 'relative_mean_difference'].abs().max()
        quad = json.loads((output/'audit/quadrature_sensitivity.json').read_text())
        appendix += (f'\nThe paired numerical-rank check uses the first 200 headline economic paths. '
                     f'Increasing rank from 256 to 512 changes mean oracle or selected regret by at most '
                     f'{100*largest:.2f} percent across all training lengths, against the predeclared '
                     '10 percent tolerance. The lower rank 128 is reported as a separate sensitivity. '
                     f'For the first {quad["replications"]} fixed headline policies, increasing independent '
                     f'population quadrature from 8,192 to 32,768 groups changes mean evaluated regret '
                     f'by at most {100*quad["max_absolute_relative_difference"]:.2f} percent '
                     '(5 percent tolerance). This latter comparison holds fitted policies and penalties fixed; '
                     'it does not reselect tuning parameters.\n')
    appendix_figures = [('population_loss_complexity', 'Population ridge loss versus population effective complexity.'),
                        ('baseline_oos_loss_uncertainty', 'OOS loss: Monte Carlo mean, median, and pointwise confidence interval for the mean.'),
                        ('baseline_oos_sharpe_uncertainty', 'OOS Sharpe: Monte Carlo mean, median, and pointwise confidence interval for the mean.'),
                        ('lambda_complexity', 'Population and empirical effective complexity as reparameterizations of regularization.'),
                        ('selected_complexity_distributions', 'Selection distributions and oracle versus selected empirical complexity.')]
    if profile=='paper':
        appendix_figures += [('appendix_N_robustness', 'Cross-sectional-size robustness at every fixed training length.'),
                             ('appendix_persistence', 'Persistence robustness.'), ('appendix_SNR', 'Signal-to-noise robustness.'),
                             ('appendix_spectral_b', 'Spectral-decay robustness across Mat\'ern smoothness values.'),
                             ('appendix_approximation_rank', 'Numerical approximation-rank sensitivity; the economic factor dimension remains three.'),
                             ('appendix_empirical_ranks', 'Empirical-rank robustness: E5 has finite support and does not have the baseline asymptotic interpretation.'),
                             ('appendix_heteroskedastic', 'Bounded heteroskedasticity: conditional pricing is not imposed and regret uses a finite-subspace reference.')]
        appendix += '\n\\input{\\simoutput/tables/appendix_spectral_rates.tex}\n'
    for name, caption in appendix_figures:
        appendix += ('\n\\begin{figure}[p]\n\\centering\n\\includegraphics[width=\\textwidth]{\\simoutput/figures/'+name+'.pdf}\n'
                     '\\caption{'+caption+'}\n\\label{fig:sim_'+name+'}\n\\end{figure}\n')
    (directory/'simulation_section.tex').write_text(text)
    (directory/'simulation_appendix.tex').write_text(appendix)
    preamble = r'''\documentclass[11pt]{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern,amsmath,amssymb,graphicx,booktabs,longtable,array}
\usepackage[margin=1in]{geometry}
\usepackage[hidelinks]{hyperref}
\newcommand{\simoutput}{..}
\title{The Law of Portfolio Learnability\\Simulation section preview}
\date{}
\begin{document}
\maketitle
\input{simulation_section.tex}
\input{simulation_appendix.tex}
\end{document}
'''
    (directory/'simulation_preview.tex').write_text(preamble)
    return directory


def compile_preview(output, profile='paper'):
    directory = generate_section(output, profile)
    command = ['latexmk','-pdf','-interaction=nonstopmode','-halt-on-error','simulation_preview.tex']
    result = subprocess.run(command, cwd=directory, capture_output=True, text=True)
    (directory/'compile_transcript.txt').write_text(result.stdout+result.stderr)
    if result.returncode:
        raise RuntimeError(f'LaTeX preview failed: {directory / "compile_transcript.txt"}')
    return directory/'simulation_preview.pdf'


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--profile',choices=['smoke','paper','confirmation_v2'],default='confirmation_v2')
    args=parser.parse_args()
    print(compile_preview(Path('simulations/outputs')/args.profile,args.profile))
