"""Advance completed preproduction evidence to the full authorized study.

The numerical rule is fixed: choose the lowest common forward-certified rank;
otherwise retain the largest investigated fixed rank and report its limitations.
No Sharpe slope, complexity slope or ex-post best penalty enters this decision.
Final completion always requires separate visual review and publication checks.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
import traceback

import numpy as np
import pandas as pd

from simulations.extended.design import OUTPUT,ENVIRONMENTS,RANKS,T_REQUIRED,T_ROBUSTNESS,BASIS_SEED,seed
from simulations.extended.audits import quadrature_audit
from simulations.extended.preflight import ensure_population
from simulations.provenance import json_write,utc_now,output_lock


def execute(module,*arguments):
    command=[sys.executable,'-m',module,*map(str,arguments)]
    print('Executing',command,flush=True)
    subprocess.run(command,check=True)


def wait_for_preflight(pid):
    while True:
        result=subprocess.run(['ps','-p',str(pid),'-o','stat=,command='],capture_output=True,text=True)
        current=result.stdout.strip()
        if not current or current.startswith('Z'):
            break
        if '-m simulations.extended.preflight' not in current:
            raise ValueError('The observed PID no longer identifies the expected preflight job.')
        time.sleep(30)
    # A terminal process alone does not prove successful scientific preflight.
    status=json.loads((OUTPUT/'preproduction_audit_status.json').read_text())
    if status['pilot_replications']!=12:
        raise ValueError('Preproduction evidence is incomplete.')
    for rank in RANKS:
        for index in range(12):
            with np.load(OUTPUT/'rank_pilot'/f'P{rank}'/f'rep_{index:03d}.npz') as z:
                if int(z['index'])!=index or int(z['rank'])!=rank:
                    raise ValueError('Invalid paired-rank pilot checkpoint.')


def select():
    table=pd.read_csv(OUTPUT/'rank_audit_theory.csv')
    selected=max(RANKS)
    forward=False
    for rank in RANKS[:-1]:
        rows=table[table.lower_rank==rank]
        passed=True
        for name in ENVIRONMENTS:
            grid=T_REQUIRED if name=='baseline' else T_ROBUSTNESS
            cells=rows[(rows.environment==name)&rows['T'].isin(grid)]
            passed &= len(cells)==len(grid) and bool(cells.lower_rank_certified.all())
        if passed:
            selected=rank;forward=True;break
    if selected!=4096:
        ensure_population(4096,131072,BASIS_SEED,seed('quadrature',1))
        quadrature_audit(selected)
    quad=pd.read_csv(OUTPUT/'quadrature_audit.csv')
    optional=table[(table.lower_rank==selected)&(table.environment=='baseline')&(table['T']==7290)]
    qoptional=quad[(quad['rank']==selected)&(quad.environment=='baseline')&(quad['T']==7290)]
    include=bool(forward and len(optional)==1 and optional.lower_rank_certified.all()
                 and len(qoptional)==1 and qoptional.quadrature_pass.all())
    decision=dict(rank=selected,include_7290=include,forward_certificate_available=forward,
        rule='Lowest common rank passing both unchanged 5% conditions at every required horizon/environment; otherwise largest investigated fixed rank with explicit unresolved-cell reporting.',
        permitted_limitation='The study request explicitly requires reporting a limitation if no single fixed investigated rank resolves all cells; the threshold and analytical optimum are not changed.',
        no_performance_rate_used=True,decided_utc=utc_now())
    json_write(OUTPUT/'rank_selection_decision.json',decision)
    return selected,include


def cleanup_regenerable_caches():
    # These are caches generated by this study, explicitly excluded from Git.
    # Preserve production operator matrices until their lossless archive exists.
    removed=0
    for path in (OUTPUT/'pilot').glob('*.npz'):
        if path.name.startswith(('basis_','integrals_')) or (path.name.startswith('operator_') and '_Q131072_' in path.name):
            removed+=path.stat().st_size
            path.unlink()
    print('Released regenerable cache bytes before portable export:',removed,flush=True)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--preflight-pid',type=int,required=True)
    args=parser.parse_args()
    with output_lock(OUTPUT/'advance_supervisor'):
        try:
            wait_for_preflight(args.preflight_pid)
            if not (OUTPUT/'protocol.json').exists():
                rank,optional=select()
                # A long-lived watcher must execute the current, fingerprinted
                # freezer in a fresh interpreter, not a stale imported body.
                arguments=['--rank',rank]
                if optional:
                    arguments.append('--include-7290')
                execute('simulations.extended.freeze',*arguments)
            workers=1
            resource=OUTPUT/'pilot'/'concurrency_probe.json'
            if resource.exists():
                result=json.loads(resource.read_text())
                if result.get('recommended_workers')==2 and shutil.disk_usage(OUTPUT).free>=1.5*1024**3:
                    workers=2
            json_write(OUTPUT/'advance_status.json',dict(stage='production',workers=workers,updated_utc=utc_now()))
            execute('simulations.extended.production','--workers',workers)
            execute('simulations.extended.summarize')
            execute('simulations.extended.verify','--data-only')
            execute('simulations.extended.report')
            execute('simulations.extended.figures')
            cleanup_regenerable_caches()
            execute('simulations.extended.archive')
            execute('simulations.extended.verify')
            json_write(OUTPUT/'advance_status.json',dict(stage='ready_for_visual_review',updated_utc=utc_now(),
                remaining='Inspect all ten final figures, review critical conclusions, update delivery documentation, commit/push all intended artifacts, and present all ten figures in chat.'))
        except Exception as exc:
            json_write(OUTPUT/'advance_status.json',dict(stage='failed',error=str(exc),traceback=traceback.format_exc(),updated_utc=utc_now()))
            raise

if __name__=='__main__':
    main()
